import Head from 'next/head'
import React, { useState } from 'react'
import styles from "@/styles/form.module.css";
import Link from "next/link";

const login = () => {
  const { mainFormSection, center_row, inputField, center_column } = styles;

  const [userData, setUserData] = useState({
    userName: "",
    userEmail: "",
    userPassword: "",
  });
  const [confirmPassword, setConfirmPassword] = useState(null);

  const handleChange = (e) => {
    setUserData({ ...userData, [e.target.name]: e.target.value });
  };
  // =========================== handle submit ==============================
  const handleSubmit = (e) => {
    e.preventDefault();
  };
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={mainFormSection + " " + center_row}>
        <form method="POST" className={center_column} onSubmit={handleSubmit}>
          <h1>Login</h1>
          {/* ======================================= Email field ===========================*/}
          <div className={inputField}>
            <label>Email</label>
            <input type="email" title="Enter Email" required placeholder=" " onChange={handleChange} />
          </div>
          {/* ======================================= Password field ===========================*/}
          <div className={inputField}>
            <label>Password</label>
            <input type="password" placeholder=" " required title="Enter Password" onChange={handleChange}/>
          </div>
          <input type="submit" value="Login" />
          <span>
            Don't have account? <Link href={"/auth/signup"}>Sign up</Link>
          </span>
        </form>
      </section>
    </>
  )
}

export default login